/**
 * linti.yaml as the configurator sees it: a form schema derived from LinTi's
 * pydantic model (site/app/data/config-schema.json, generated by
 * scripts/generate_all_rules.py) plus helpers that edit the YAML document in
 * place, so comments and key order survive form changes.
 */
import { isMap, isPair, isScalar, parseDocument, YAMLMap } from 'yaml'
import type { Document } from 'yaml'
import configSchema from '../data/config-schema.json'
import rules from '../data/rules.json'

export type ConfigPath = string[]
export type FieldKind = 'boolean' | 'integer' | 'string' | 'enum' | 'list'

export type FieldSpec = {
  key: string
  path: ConfigPath
  kind: FieldKind
  label: string
  description: string
  options: string[]
  nullable: boolean
  default: unknown
  /** Accepted by LinTi but not offered in the form unless it is already set. */
  hidden: boolean
  /** A `Severity`: LinTi drops an invalid value with a warning instead of failing. */
  tolerant: boolean
}

export type RuleSummary = {
  id: string
  name: string
  description: string
  group: string
  group_name: string
  severity: string
  auto_fix: boolean
  enabled_by_default: boolean
  config_key: string
}

export type RuleCard = {
  configKey: string
  title: string
  description: string
  group: string
  groupName: string
  rules: RuleSummary[]
  fields: FieldSpec[]
}

export type ConfigIssue = { path: ConfigPath, level: 'error' | 'warning', message: string }

export type ParsedConfig = {
  doc: Document
  data: Record<string, unknown>
  /** Syntax errors; while there are any, the form must not write to the YAML. */
  parseErrors: { from: number, to: number, message: string }[]
}

export type Preset = { key: string, title: string, description: string, yaml: string }

type SchemaNode = {
  $ref?: string
  anyOf?: SchemaNode[]
  type?: string
  enum?: string[]
  title?: string
  description?: string
  properties?: Record<string, SchemaNode>
  'x-hidden'?: boolean
}

const schema = configSchema.schema as unknown as SchemaNode & { $defs: Record<string, SchemaNode> }
const defaults = configSchema.defaults as Record<string, unknown>
const allRules = rules as RuleSummary[]

export const presets = configSchema.presets as Preset[]
const removedRuleConfigs = configSchema.removed_rule_configs as Record<string, string>
const movedToTopLevel = configSchema.moved_to_toplevel as Record<string, { setting: string, top_level: string }>

function deref(node: SchemaNode): SchemaNode {
  return node.$ref ? schema.$defs[node.$ref.split('/').pop()!]! : node
}

function getPath(data: unknown, path: ConfigPath): unknown {
  let node = data
  for (const key of path) {
    if (!node || typeof node !== 'object' || Array.isArray(node)) return undefined
    node = (node as Record<string, unknown>)[key]
  }
  return node
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === 'object' && !Array.isArray(value)
}

export function sameValue(a: unknown, b: unknown): boolean {
  return JSON.stringify(a ?? null) === JSON.stringify(b ?? null)
}

function humanize(key: string) {
  const text = key.replace(/_/g, ' ')
  return text.charAt(0).toUpperCase() + text.slice(1)
}

function fieldSpec(key: string, path: ConfigPath, property: SchemaNode, fallback: unknown): FieldSpec {
  const members = property.anyOf ?? [property]
  const concrete = members.filter(member => member.type !== 'null')
  const node = deref(concrete[0] ?? property)
  const kind: FieldKind = node.enum
    ? 'enum'
    : node.type === 'boolean'
      ? 'boolean'
      : node.type === 'integer'
        ? 'integer'
        : node.type === 'array' ? 'list' : 'string'
  const declared = getPath(defaults, path)
  return {
    key,
    path,
    kind,
    label: humanize(key),
    // Only the field's own text: a $ref'd enum's description is its class docstring.
    description: property.description ?? '',
    options: node.enum ?? [],
    nullable: concrete.length < members.length,
    default: declared === undefined ? fallback : declared,
    hidden: !!property['x-hidden'],
    tolerant: !!concrete[0]?.$ref?.endsWith('/Severity'),
  }
}

const rulesSchema = deref(schema.properties!.rules!)
const baseRuleSchema = schema.$defs.RuleConfig!

/** Run-level settings (everything outside `rules:`), split into common and limits. */
export const topLevelFields: FieldSpec[] = Object.entries(schema.properties!)
  .filter(([key]) => key !== 'rules')
  .map(([key, property]) => fieldSpec(key, [key], property, null))
export const runFields = topLevelFields.filter(field => !field.key.startsWith('max_'))
export const limitFields = topLevelFields.filter(field => field.key.startsWith('max_'))

function ruleFields(configKey: string, enabledByDefault: boolean): FieldSpec[] {
  const typed = rulesSchema.properties?.[configKey]
  const node = typed ? deref(typed) : baseRuleSchema
  return Object.entries(node.properties ?? {}).map(([key, property]) =>
    fieldSpec(key, ['rules', configKey, key], property, key === 'enabled' ? enabledByDefault : null),
  )
}

/** One card per `rules.<key>` block, in rule-reference order. */
export const ruleCards: RuleCard[] = (() => {
  const cards = new Map<string, RuleCard>()
  for (const rule of allRules) {
    const card = cards.get(rule.config_key)
    if (card) {
      card.rules.push(rule)
      continue
    }
    cards.set(rule.config_key, {
      configKey: rule.config_key,
      title: rule.name,
      description: rule.description,
      group: rule.group,
      groupName: rule.group_name,
      rules: [rule],
      fields: ruleFields(rule.config_key, rule.enabled_by_default),
    })
  }
  for (const card of cards.values()) {
    // A key shared by several rules (whitespace: F220–F270) is named after the key.
    if (card.rules.length > 1) {
      card.title = humanize(card.configKey)
      card.description = card.rules.map(rule => rule.name).join(', ')
    }
  }
  return [...cards.values()]
})()

const knownTopLevel = new Set(Object.keys(schema.properties!))
const knownRuleKeys = new Set([...Object.keys(rulesSchema.properties ?? {}), ...ruleCards.map(card => card.configKey)])
const fieldsByRule = new Map(ruleCards.map(card => [card.configKey, card.fields]))

/** The value LinTi uses for *field*: what the YAML sets, else the default. */
export function effectiveValue(data: Record<string, unknown>, field: FieldSpec): unknown {
  const value = getPath(data, field.path)
  return value === undefined ? field.default : value
}

/** Whether the YAML sets *field* to something other than its default. */
export function isChanged(data: Record<string, unknown>, field: FieldSpec): boolean {
  const value = getPath(data, field.path)
  return value !== undefined && !sameValue(value, field.default)
}

export function parseConfig(text: string): ParsedConfig {
  const doc = parseDocument(text, { prettyErrors: false })
  const parseErrors = doc.errors.map(error => ({
    from: error.pos[0],
    to: Math.max(error.pos[1], error.pos[0] + 1),
    message: error.message.split('\n')[0]!,
  }))
  const data = parseErrors.length ? {} : doc.toJS()
  if (!parseErrors.length && data !== null && !isPlainObject(data)) {
    // A list or bare value: the form has nothing it could safely edit.
    const range = (doc.contents as { range?: [number, number, number] } | null)?.range
    parseErrors.push({
      from: range?.[0] ?? 0,
      to: Math.max(range?.[1] ?? 1, (range?.[0] ?? 0) + 1),
      message: 'linti.yaml must be a mapping of settings at the top level.',
    })
  }
  return { doc, data: isPlainObject(data) ? data : {}, parseErrors }
}

/** Serialize *doc*; an emptied mapping becomes an empty file, not `{}`. */
export function stringifyConfig(doc: Document): string {
  if (!doc.contents || (isMap(doc.contents) && !doc.contents.items.length)) {
    const comment = [doc.commentBefore, doc.comment].filter(Boolean).join('\n\n')
    return comment ? `${comment.replace(/^/gm, '#')}\n` : ''
  }
  return doc.toString({ lineWidth: 0 })
}

/**
 * Write *value* at *path*, or remove the key when it equals *defaultValue*, so
 * the file keeps listing only deviations from LinTi's defaults.
 */
export function setOption(doc: Document, path: ConfigPath, value: unknown, defaultValue: unknown) {
  if (sameValue(value, defaultValue)) {
    // Nothing to remove below a missing or empty (`whitespace:`) parent.
    const parent = path.length > 1 ? doc.getIn(path.slice(0, -1), true) : doc.contents
    if (!isMap(parent)) return
    parent.delete(path.at(-1))
    // Drop the `rules.<key>:` / `rules:` blocks this may have emptied.
    for (let depth = path.length - 1; depth > 0; depth--) {
      const parent = doc.getIn(path.slice(0, depth), true)
      if (isMap(parent) && !parent.items.length) doc.deleteIn(path.slice(0, depth))
    }
    return
  }
  // A missing, empty or scalar parent (`rules:` with nothing below) becomes a mapping.
  if (!isMap(doc.contents)) doc.contents = new YAMLMap() as never
  for (let depth = 1; depth < path.length; depth++) {
    const prefix = path.slice(0, depth)
    if (!isMap(doc.getIn(prefix, true))) doc.setIn(prefix, new YAMLMap())
  }
  doc.setIn(path, value)
}

/** Character range of the key/value at *path*, for editor diagnostics. */
export function rangeOf(doc: Document, path: ConfigPath): { from: number, to: number } | null {
  let node: unknown = doc.contents
  let range: { from: number, to: number } | null = null
  for (const key of path) {
    if (!isMap(node)) break
    const pair = node.items.find(item => isPair(item) && isScalar(item.key) && String(item.key.value) === key)
    if (!pair) break
    const keyRange = (pair.key as { range?: [number, number, number] }).range
    const valueRange = (pair.value as { range?: [number, number, number] } | null)?.range
    if (keyRange) range = { from: keyRange[0], to: valueRange?.[1] ?? keyRange[1] }
    node = pair.value
  }
  return range
}

function checkValue(field: FieldSpec, value: unknown, issues: ConfigIssue[]) {
  if (value === null && field.nullable) return
  const where = field.path.join('.')
  if (field.tolerant) {
    if (typeof value !== 'string' || !field.options.includes(value)) {
      issues.push({
        path: field.path,
        level: 'warning',
        message: `Invalid severity ${JSON.stringify(value)} for '${where}'; expected ${field.options.join(' or ')}. LinTi falls back to the default.`,
      })
    }
    return
  }
  const wrong = (expected: string) => issues.push({ path: field.path, level: 'error', message: `'${where}' must be ${expected}; LinTi rejects this file.` })
  switch (field.kind) {
    case 'boolean':
      if (typeof value !== 'boolean') wrong('true or false')
      break
    case 'integer':
      if (typeof value !== 'number' || !Number.isInteger(value)) wrong('a whole number')
      break
    case 'enum':
      if (typeof value !== 'string' || !field.options.includes(value)) wrong(`one of ${field.options.join(', ')}`)
      break
    case 'list':
      if (!Array.isArray(value) || value.some(item => typeof item !== 'string')) wrong('a list of strings')
      break
    default:
      if (typeof value !== 'string') wrong('a string')
  }
}

/** Problems LinTi would report (or silently ignore) when loading *data*. */
export function validateConfig(data: Record<string, unknown>): ConfigIssue[] {
  const issues: ConfigIssue[] = []
  for (const [key, value] of Object.entries(data)) {
    if (!knownTopLevel.has(key)) {
      issues.push({ path: [key], level: 'warning', message: `Unknown setting '${key}'; LinTi ignores it.` })
      continue
    }
    if (key === 'rules') continue
    checkValue(topLevelFields.find(field => field.key === key)!, value, issues)
  }

  const ruleBlock = data.rules
  if (ruleBlock === undefined || ruleBlock === null) return issues
  if (!isPlainObject(ruleBlock)) {
    issues.push({ path: ['rules'], level: 'error', message: `'rules' must be a mapping of rule settings; LinTi rejects this file.` })
    return issues
  }
  for (const [ruleKey, settings] of Object.entries(ruleBlock)) {
    const path = ['rules', ruleKey]
    if (removedRuleConfigs[ruleKey]) {
      issues.push({ path, level: 'warning', message: removedRuleConfigs[ruleKey]! })
      continue
    }
    if (!knownRuleKeys.has(ruleKey)) {
      issues.push({ path, level: 'warning', message: `Unknown rule '${ruleKey}'; no rule reads this setting.` })
      continue
    }
    if (settings === null) continue
    if (!isPlainObject(settings)) {
      issues.push({ path, level: 'error', message: `'rules.${ruleKey}' must be a mapping; LinTi rejects this file.` })
      continue
    }
    const fields = fieldsByRule.get(ruleKey) ?? []
    for (const [option, value] of Object.entries(settings)) {
      const field = fields.find(item => item.key === option)
      if (!field) {
        issues.push({ path: [...path, option], level: 'warning', message: `Unknown option '${option}' for rule '${ruleKey}'; LinTi ignores it.` })
        continue
      }
      checkValue(field, value, issues)
    }
    const moved = movedToTopLevel[ruleKey]
    const deprecated = moved && settings[moved.setting]
    if (moved && Array.isArray(deprecated) && deprecated.length) {
      const both = Array.isArray(data[moved.top_level]) && (data[moved.top_level] as unknown[]).length
      issues.push({
        path: [...path, moved.setting],
        level: both ? 'error' : 'warning',
        message: both
          ? `Both the top-level '${moved.top_level}' and the deprecated 'rules.${ruleKey}.${moved.setting}' are set; LinTi rejects this file. Keep only the top-level setting.`
          : `'rules.${ruleKey}.${moved.setting}' is deprecated; move it to the top-level '${moved.top_level}' setting.`,
      })
    }
  }
  return issues
}

/** base64url of the UTF-8 text, for `#config=` share links. */
export function encodeShare(text: string): string {
  let binary = ''
  for (const byte of new TextEncoder().encode(text)) binary += String.fromCharCode(byte)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

export function decodeShare(value: string): string | null {
  try {
    const binary = atob(value.replace(/-/g, '+').replace(/_/g, '/'))
    return new TextDecoder('utf-8', { fatal: true }).decode(Uint8Array.from(binary, char => char.charCodeAt(0)))
  } catch {
    return null
  }
}

/** A preset's YAML with a header comment naming it. */
export function presetText(preset: Preset): string {
  const header = `# linti.yaml – ${preset.title}\n# Settings not listed here keep LinTi's defaults.\n`
  return preset.yaml ? `${header}\n${preset.yaml}` : header
}
