#!/usr/bin/env python3
"""Generate ALL_RULES.md (and the site's rules.json) from rule metadata.

Usage:
    python scripts/generate_all_rules.py          # write ALL_RULES.md + site rules.json
    python scripts/generate_all_rules.py --check   # check both are up-to-date
"""

from __future__ import annotations

import sys
from pathlib import Path
from textwrap import dedent

# Ensure the package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from linti.linter.lint_issue import Severity  # noqa: E402
from linti.rules.examples import describe_context  # noqa: E402
from linti.rules.Rule import RuleMetadata  # noqa: E402
from linti.rules.rule_ids import GROUP_NAMES, deprecated_ids_for, rule_docs  # noqa: E402

# The site's rules.json is generated from the same rule_docs(); regenerating
# one without the other would leave the test suite red.
import export_rule_reference  # noqa: E402  (sibling script; its dir is on sys.path)

FILE_BANNER = dedent("""\
    <!-- This file is auto-generated by scripts/generate_all_rules.py. Do not edit directly. -->
    <!-- Rule content is sourced from the rule models under src/rules; fix issues there (or add new rules there) and regenerate this file. -->
""")

HEADER = dedent("""\
    # Linti Rule IDs

    Rule IDs consist of a letter indicating the rule group, followed by a 3-digit number.

    ## Rule Groups

    {group_list}

    ## Current Rules
""")

TABLE_HEADER = dedent("""\
    | Rule ID | Rule Name | Description | Auto-fix | Severity |
    |---------|-----------|-------------|----------|----------|
""")

#: Top-level settings that belong in the example but that no rule declares,
#: because they govern the run rather than any single rule. Rendered ahead of
#: the settings collected from the rules' own config_example snippets.
RUN_LEVEL_CONFIG = dedent("""\
    # Lowest severity that makes the run fail. Findings below it are still
    # reported, but exit 0 (--fail-on on the CLI).
    fail_on: error         # error (default) | warning
    # Lowest severity that is reported at all. Anything below is dropped before
    # the report is built, so it cannot fail the run either (--severity).
    severity: warning      # warning (default) | error
    # Whether a directory or glob scan may follow a symlink out of the tree it
    # was pointed at. Off by default, so --auto-fix only ever writes inside
    # that tree; such links are skipped with a warning instead.
    follow_external_symlinks: false   # false (default) | true
""")

CONFIG_SECTION = dedent("""\
    ## Configuration

    The linter can be configured using a `linti.yaml` configuration file. The file is automatically discovered and loaded from the same directory as the TI file being analyzed.

    ### Automatic Configuration Discovery

    Place a `linti.yaml` file in the same directory as your TI files:

    ```bash
    my-project/
    \u251c\u2500\u2500 processes/
    \u2502   \u251c\u2500\u2500 linti.yaml          # Configuration for this directory
    \u2502   \u251c\u2500\u2500 process1.ti
    \u2502   \u2514\u2500\u2500 process2.ti
    ```

    When you run `linti processes/process1.ti`, the linter will automatically find and use `linti.yaml`.

    ### Custom Configuration File

    You can also specify a custom configuration file:

    ```bash
    linti process.ti --config custom-config.yaml
    ```

    ### Complete Configuration Example

    A typical `linti.yaml` file looks like this:

    ```yaml
    {top_level_config}rules:
    {merged_config}
    ```

    ### Disabling and Reweighting Rules

    Every rule accepts `enabled` and `severity`, whatever else it adds on top:

    ```yaml
    rules:
      keyword_casing:
        enabled: false
      variable_prefix:
        enabled: true
      unknown_statement:
        severity: error    # promote E110 from warning to blocking
    ```

    `severity` left unset keeps whatever the rule declares (the Severity column
    above); naming a value here overrides it for this project.

    ## CLI Usage

    ### Basic Usage

    ```bash
    # Lint a single file
    linti process.ti

    # Lint with additional debug output
    linti process.ti --tokens
    linti process.ti --ast
    linti process.ti --tokens --ast

    # Lint with custom configuration
    linti process.ti --config my-config.yaml

    # Severity control (overrides fail_on / severity from the config)
    linti process.ti --fail-on warning   # fail on warnings too
    linti process.ti --severity error    # only report errors
    ```

    ### Exit Codes

    The CLI returns different exit codes based on linting results:
    - `0`: No linting issues found, or only findings below `fail_on`
    - `1`: At least one finding at or above `fail_on` (default: `error`)

    Warnings therefore do not fail a run by default — pass `--fail-on warning`
    to block on them too. This allows integration with CI/CD pipelines and
    automated workflows.
""")


def _render_group_list() -> str:
    """Render the ``## Rule Groups`` legend from GROUP_NAMES."""
    return "\n".join(f"- **{group}** - {name}" for group, name in GROUP_NAMES.items())


def _collect_rules() -> list[tuple[str, RuleMetadata]]:
    """Collect all documented rules (registry and synthetic), sorted by rule ID."""
    return [(doc.rule_id, doc.metadata) for doc in rule_docs()]


def _render_summary_tables(rules: list[tuple[str, RuleMetadata]]) -> str:
    """Render the per-group summary tables."""
    parts: list[str] = []
    current_group = ""

    for rule_id, meta in rules:
        group = rule_id[0]
        if group != current_group:
            name = GROUP_NAMES.get(group, "Other")
            heading = f"{name} ({group})"
            parts.append(f"\n### {heading}\n\n{TABLE_HEADER.rstrip()}")
            current_group = group
        auto_fix = "\u2705" if meta.auto_fix else "\u274c"
        name = meta.name + (" (deprecated)" if meta.deprecated_by else "")
        parts.append(
            f"| {rule_id} | {name} | {meta.description} | {auto_fix} "
            f"| {meta.severity.value} |"
        )

    return "\n".join(parts).lstrip("\n")


def _render_examples(label: str, lang: str, examples: list) -> str:
    """Render a code block of examples."""
    if not examples:
        return ""
    lines = [f"**{label}:**", f"```{lang}"]
    for ex in examples:
        if ex.description:
            lines.append(f"# {ex.description}")
        context = describe_context(ex)
        if context:
            lines.append(f"# Context: {context}")
        lines.append(ex.code)
    lines.extend(["```", ""])
    return "\n".join(lines)


def _render_rule_detail(rule_id: str, meta: RuleMetadata) -> str:
    """Render the detailed section for a single rule."""
    parts = [f"### {rule_id}: {meta.name}", "", f"{meta.description}.", ""]

    if meta.deprecated_by:
        parts.extend([f"> Deprecated: use {meta.deprecated_by} instead.", ""])

    previous = deprecated_ids_for(rule_id)
    if previous:
        joined = ", ".join(previous)
        parts.append(f"> Previous rule ID: {joined} (deprecated)")
        parts.append("")

    if meta.auto_fix:
        parts.append(
            "**\u2728 Auto-fix available:** Use `linti --auto-fix` to automatically fix issues."
        )
        parts.append("")

    if meta.severity is Severity.WARNING:
        parts.append(
            "**\u26a0 Severity: warning** \u2014 reported but does not fail the run. Pass "
            "`--fail-on warning` to block on it, or set "
            "`rules.<key>.severity: error` in `linti.yaml`."
        )
        parts.append("")

    if meta.explanation:
        for paragraph in meta.explanation.split("\n\n"):
            parts.append(paragraph)
            parts.append("")

    if meta.config_example:
        parts.extend(["**Configuration:**", "```yaml", meta.config_example, "```", ""])

    valid = [e for e in meta.examples if e.valid]
    invalid = [e for e in meta.examples if not e.valid]

    if valid:
        parts.append(_render_examples("Valid usage", "ti", valid))
    if invalid:
        parts.append(_render_examples("Invalid usage", "ti", invalid))

    parts.extend(["---", ""])
    return "\n".join(parts)


def _split_config_example(config_example: str) -> tuple[list[str], list[str]]:
    """Split a rule's config_example into its top-level and per-rule lines.

    A snippet may set top-level keys (e.g. C510's ``target_version``) before its
    ``rules:`` block.  Both halves are needed: dropping the top-level lines
    leaves the merged example referring to a setting it never defines.
    """
    top_level: list[str] = []
    rule_lines: list[str] = []
    inside_rules = False
    for line in config_example.split("\n"):
        if line.strip() == "rules:":
            inside_rules = True
            continue
        (rule_lines if inside_rules else top_level).append(line)
    return top_level, rule_lines


def _render_merged_config(rules: list[tuple[str, RuleMetadata]]) -> str:
    """Merge all config_example snippets into one combined rules: block."""
    parts: list[str] = []
    for _, meta in rules:
        if not meta.config_example:
            continue
        parts.extend(_split_config_example(meta.config_example)[1])
        parts.append("")
    return "\n".join(parts)


def _render_top_level_config(rules: list[tuple[str, RuleMetadata]]) -> str:
    """Collect the top-level settings the rules' config examples rely on.

    Starts from the run-level settings, which govern the whole run and belong in
    the example even though no rule declares them, then appends what the rules
    ask for.  Duplicates are dropped so two rules sharing a setting (as
    version-aware rules will) emit it once.
    """
    lines: list[str] = RUN_LEVEL_CONFIG.rstrip("\n").split("\n")
    for _, meta in rules:
        if not meta.config_example:
            continue
        for line in _split_config_example(meta.config_example)[0]:
            if line.strip() and line not in lines:
                lines.append(line)
    return "\n".join(lines) + "\n" if lines else ""


def generate_markdown() -> str:
    """Generate the complete ALL_RULES.md content."""
    rules = _collect_rules()

    sections = [
        FILE_BANNER,
        "",
        HEADER.format(group_list=_render_group_list()),
        _render_summary_tables(rules),
        "",
        "## Rule Details",
        "",
        "\n".join(_render_rule_detail(rid, meta) for rid, meta in rules),
        CONFIG_SECTION.format(
            top_level_config=_render_top_level_config(rules),
            merged_config=_render_merged_config(rules),
        ),
    ]

    return "\n".join(sections).rstrip("\n") + "\n"


def main() -> None:
    check_mode = "--check" in sys.argv

    content = generate_markdown()
    target = Path(__file__).resolve().parent.parent / "ALL_RULES.md"

    if check_mode:
        ok = True
        if not target.exists():
            print("ALL_RULES.md does not exist. Run without --check to generate it.")
            ok = False
        elif target.read_text() != content:
            print(
                "ALL_RULES.md is out of date. Run 'python scripts/generate_all_rules.py' to update."
            )
            ok = False
        else:
            print("ALL_RULES.md is up-to-date.")
        if export_rule_reference.is_up_to_date():
            print("Rule reference is up to date.")
        else:
            print(
                "Site rule reference is out of date. "
                "Run 'python scripts/generate_all_rules.py' to update."
            )
            ok = False
        sys.exit(0 if ok else 1)
    else:
        target.write_text(content)
        print(f"Generated {target}")
        export_rule_reference.write()


if __name__ == "__main__":
    main()
