#!/usr/bin/env python3
"""Generate linti.schema.json (the JSON Schema for linti.yaml) from the config models.

The schema has its own version (``SCHEMA_VERSION`` in
``src/linti/_schema_version.py``): the release in which the config last
changed. Its ``$id`` points at that release tag, so users pinning it are only
asked to update when the config really changed.

Regenerating keeps the version while the config structure is unchanged
(description-only edits included). When the structure changed, the version
becomes the one in pyproject.toml — which therefore has to be a version that
is not released yet.

Usage:
    python scripts/generate_config_schema.py                 # write the files
    python scripts/generate_config_schema.py --check         # fail if stale
    python scripts/generate_config_schema.py --check --verify-tag
        # additionally fail if the release tag of SCHEMA_VERSION exists but
        # serves a structurally different schema (needs git + network)
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

# Ensure the package is importable
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from linti._schema_version import SCHEMA_VERSION  # noqa: E402
from linti.config_schema import render_config_schema, schema_fingerprint  # noqa: E402
from linti.schema_reference import version_key  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO_ROOT / "linti.schema.json"
VERSION_MODULE = REPO_ROOT / "src" / "linti" / "_schema_version.py"

VERSION_MODULE_TEMPLATE = """\
# Generated by scripts/generate_config_schema.py. Do not edit directly.
#: The linti version whose release tag serves the current config JSON Schema,
#: i.e. the release in which the config last changed.
SCHEMA_VERSION = "{version}"
"""


def project_version() -> str:
    """The version in pyproject.toml.

    Read from the file rather than the installed metadata, which an editable
    install only refreshes on reinstall and would lag behind a version bump.
    """
    pyproject = (REPO_ROOT / "pyproject.toml").read_text()
    match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject, re.MULTILINE)
    if match is None:
        raise SystemExit("No version found in pyproject.toml")
    return match.group(1)


def _committed_fingerprint() -> str | None:
    try:
        return schema_fingerprint(json.loads(SCHEMA_PATH.read_text()))
    except (OSError, ValueError):
        return None


def generate() -> int:
    schema_version = SCHEMA_VERSION
    current = render_config_schema(schema_version)
    if schema_fingerprint(json.loads(current)) != _committed_fingerprint():
        schema_version = project_version()
        if version_key(schema_version) < version_key(SCHEMA_VERSION):
            raise SystemExit(
                f"pyproject.toml version {schema_version} is older than the "
                f"schema version {SCHEMA_VERSION}."
            )
        current = render_config_schema(schema_version)
        print(f"Config structure changed: schema version is now {schema_version}")

    SCHEMA_PATH.write_text(current)
    VERSION_MODULE.write_text(VERSION_MODULE_TEMPLATE.format(version=schema_version))
    print(f"Wrote {SCHEMA_PATH.name} (schema version {schema_version})")
    return 0


def check() -> int:
    if not SCHEMA_PATH.exists() or SCHEMA_PATH.read_text() != render_config_schema():
        print(
            f"{SCHEMA_PATH.name} is out of date. "
            "Run: python scripts/generate_config_schema.py"
        )
        return 1
    print(f"{SCHEMA_PATH.name} is up to date (schema version {SCHEMA_VERSION}).")
    return 0


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )


def verify_tag() -> int:
    """Fail when tag v<SCHEMA_VERSION> is released with a different schema.

    That happens when the config changed while pyproject.toml still carried
    an already-released version: the URL in ``$id`` would serve the old
    schema. Not released yet is fine — the release will serve this one.
    """
    tag = f"v{SCHEMA_VERSION}"
    remote = _git("ls-remote", "--tags", "origin", f"refs/tags/{tag}")
    if remote.returncode != 0:
        print(f"Cannot query tags from origin: {remote.stderr.strip()}")
        return 1
    if not remote.stdout.strip():
        print(f"Tag {tag} is not released yet; nothing to verify.")
        return 0

    fetched = _git("fetch", "--quiet", "--depth=1", "origin", f"refs/tags/{tag}")
    released = _git("show", f"FETCH_HEAD:{SCHEMA_PATH.name}")
    released_fingerprint = None
    if fetched.returncode == 0 and released.returncode == 0:
        try:
            released_fingerprint = schema_fingerprint(json.loads(released.stdout))
        except ValueError:
            pass
    if released_fingerprint != _committed_fingerprint():
        print(
            f"The config changed, but schema version {SCHEMA_VERSION} is already "
            f"released as {tag} with a different schema. Bump the version in "
            "pyproject.toml, then run: python scripts/generate_config_schema.py"
        )
        return 1
    print(f"Tag {tag} serves this schema.")
    return 0


def main() -> int:
    if "--check" not in sys.argv:
        return generate()
    status = check()
    if status == 0 and "--verify-tag" in sys.argv:
        status = verify_tag()
    return status


if __name__ == "__main__":
    sys.exit(main())
