# Generated by scripts/generate_config_schema.py. Do not edit directly.
#: The linti version whose release tag serves the current config JSON Schema,
#: i.e. the release in which the config last changed.
SCHEMA_VERSION = "0.8.0"
